{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyM3vAl0f2imk/7ncjHEyZ/K"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":7,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3vRlP7pvJrdH","executionInfo":{"status":"ok","timestamp":1704887926554,"user_tz":-330,"elapsed":8250,"user":{"displayName":"Robin Raj","userId":"13779324533089785610"}},"outputId":"5496dd74-567b-4ad1-ccbc-bf57f51096bc"},"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting DataExplorer\n","  Downloading dataexplorer-1.0.1-py3-none-any.whl (2.3 kB)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from DataExplorer) (1.23.5)\n","Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from DataExplorer) (1.5.3)\n","Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->DataExplorer) (2.8.2)\n","Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->DataExplorer) (2023.3.post1)\n","Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->DataExplorer) (1.16.0)\n","Installing collected packages: DataExplorer\n","Successfully installed DataExplorer-1.0.1\n"]}],"source":["!pip install DataExplorer"]},{"cell_type":"code","source":["from DataExplorer import DataExplorer"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"3OIPIZZ8MASc","executionInfo":{"status":"ok","timestamp":1704887215842,"user_tz":-330,"elapsed":785,"user":{"displayName":"Robin Raj","userId":"13779324533089785610"}},"outputId":"5fd466cd-1ba7-4590-ee09-e408f13df8ff"},"execution_count":6,"outputs":[{"output_type":"execute_result","data":{"text/plain":["http://7d7e75d87728:40000/dtale/main/1"]},"metadata":{},"execution_count":6}]}]}